### ISSUE TITLE
Crashes with the latest vim-mode-plus

### ISSUE THREAD

**Issue by dionyziz** [ashthespy/Atom-LaTeX#135] opened 2018-02-05 10:25 UTC
Even though the issue with the previous version of `vim-mode-plus` was addressed in #132, the latest update to `atom-latex` (0.8.4) and `vim-mode-plus` (1.28.0) causes this bug to reappear.

To reproduce:

1. Enable both `atom-latex` and `vim-mode-plus` and upgrade to the latest versions.
2. Open a `.tex` document
3. Trying typing `$\$`

Expected behavior: The text is typed correctly.
Actual behavior: The editor crashes.

**Comment by ashthespy** [comment] 2018-02-05 12:23
@dionyziz  Can you share what shows up in the debug console?
I just tried installing [`vim-mode-plus v1.28.0`](https://atom.io/packages/vim-mode-plus)  and couldn't reproduce your error. I would advise to open up an issue its repo as well, to speed up figuring out the cause.

**Comment by dionyziz** [comment] 2018-02-23 08:28
I do not have an error in the debug console, because the editor hangs as soon as I type `\`. It looks like the screenshot attached.

<img width="792" alt="screen shot 2018-02-23 at 10 27 34" src="https://user-images.githubusercontent.com/544572/36584876-382bce06-1884-11e8-99dd-fa59e3273ef0.png">

**Comment by ashthespy** [comment] 2018-02-23 11:40
@dionyziz  Again, I just installed vim-mode-plus, and everything seemed normal when trying your triggers `$ \$` 
Could you possible share the entries for `atom-latex` and `vim-mode-plus` from your `config.cson`, so that I can try and reproduce?

**Comment by ashthespy** [comment] 2018-03-15 17:51
@dionyziz closing as I can't reproduce this without your inputs.

**Comment by dionyziz** [comment] 2018-10-15 11:28
I have been able to reproduce the above issue with all other plugins disabled, outside of vim-mode-plus and atom-latex.

**Comment by ashthespy** [comment] 2018-10-15 12:05
@dionyziz I just tried with the default the default `vim-mode-plus` installations. Couldn't reproduce. 
As I don't really use that plugin, Can you give me minimal settings/steps to reproduce? 
Here is what I managed:
![vim-mode](https://user-images.githubusercontent.com/16233271/46949931-56c75f80-d083-11e8-8fb8-2d611ab3794d.gif)

**Comment by dionyziz** [comment] 2018-10-15 17:59
Is it possible to just disable everything outside of LaTeX highlighting for this package? In particular I would like to disable auto-completion/suggestions to see if the issue pertains to that.

**Comment by ashthespy** [comment] 2018-10-15 19:49
@dionyziz do you have a lot of files in your project dir?
In that case the file watcher module we use could be having issues.

You could disable the watcher module, (albeit at the cost of more filesystem IO operations). To do this, add a `disable_watcher:true` to your `config.cson` (Found from `File`→`Config...`) under the Atom-Latex object - something like:
```
  "atom-latex":
    bibtex: "biber"
    disable_watcher: true
```

**Closed** 2019-07-31 20:51 UTC
Labels: more-info-needed
