### ISSUE TITLE
Bad request for Atom Latex: Preview

### ISSUE THREAD

**Issue by leandrochiarini** [ashthespy/Atom-LaTeX#239] opened 2020-03-09 10:56 UTC
Hello,

I am using Manjaro XFCE 19.0.2. Atom-latex builds just fine and the pdf is saved properly in the page, however, the Atom latex:preview returns a blank page with the text "Bad Request".  

I disabled all other community packages in my atom, however, the problem persist. I am using version 0.9.1. This is my first time submitting an Issue, is this enough information?

I appreciate any help,

Best,
Leandro

EDIT: I am using Atom version 1.44.0,

**Comment by ashthespy** [comment] 2020-03-09 11:20
Dupe of #237 
tl;dr - use  [`atom-editor-bin`](https://aur.archlinux.org/packages/atom-editor-bin/) to avoid such issues..

**Closed** 2020-03-09 11:21 UTC
